E0412 02:01:37.143214   30872 cache.go:63] save image to file "k8s.gcr.io/kube-apiserver:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-apiserver_v1.18.0" failed: nil image for k8s.gcr.io/kube-apiserver:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.143214   30872 cache.go:63] save image to file "k8s.gcr.io/kube-proxy:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-proxy_v1.18.0" failed: nil image for k8s.gcr.io/kube-proxy:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.146163   30872 cache.go:63] save image to file "k8s.gcr.io/coredns:1.6.7" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\coredns_1.6.7" failed: nil image for k8s.gcr.io/coredns:1.6.7: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.148125   30872 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-controller-manager_v1.18.0" failed: nil image for k8s.gcr.io/kube-controller-manager:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.150071   30872 cache.go:63] save image to file "k8s.gcr.io/pause:3.2" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\pause_3.2" failed: nil image for k8s.gcr.io/pause:3.2: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.157896   30872 cache.go:63] save image to file "k8s.gcr.io/etcd:3.4.3-0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\etcd_3.4.3-0" failed: nil image for k8s.gcr.io/etcd:3.4.3-0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.159823   30872 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-scheduler_v1.18.0" failed: nil image for k8s.gcr.io/kube-scheduler:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.172538   30872 cache.go:63] save image to file "gcr.io/k8s-minikube/storage-provisioner:v1.8.1" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\gcr.io\\k8s-minikube\\storage-provisioner_v1.8.1" failed: nil image for gcr.io/k8s-minikube/storage-provisioner:v1.8.1: Get https://gcr.io/v2/: dial tcp [2404:6800:4008:c00::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:01:37.172538   30872 cache.go:126] Error caching images:  Caching images for kubeadm: caching images: caching image "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-apiserver_v1.18.0": nil image for k8s.gcr.io/kube-apiserver:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.552817   30872 cache.go:63] save image to file "k8s.gcr.io/pause:3.2" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\pause_3.2" failed: nil image for k8s.gcr.io/pause:3.2: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.560597   30872 cache.go:63] save image to file "k8s.gcr.io/etcd:3.4.3-0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\etcd_3.4.3-0" failed: nil image for k8s.gcr.io/etcd:3.4.3-0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.572339   30872 cache.go:63] save image to file "gcr.io/k8s-minikube/storage-provisioner:v1.8.1" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\gcr.io\\k8s-minikube\\storage-provisioner_v1.8.1" failed: nil image for gcr.io/k8s-minikube/storage-provisioner:v1.8.1: Get https://gcr.io/v2/: dial tcp [2404:6800:4008:c00::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.576252   30872 cache.go:63] save image to file "k8s.gcr.io/kube-proxy:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-proxy_v1.18.0" failed: nil image for k8s.gcr.io/kube-proxy:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.576252   30872 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-scheduler_v1.18.0" failed: nil image for k8s.gcr.io/kube-scheduler:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.581103   30872 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-controller-manager_v1.18.0" failed: nil image for k8s.gcr.io/kube-controller-manager:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.586994   30872 cache.go:63] save image to file "k8s.gcr.io/coredns:1.6.7" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\coredns_1.6.7" failed: nil image for k8s.gcr.io/coredns:1.6.7: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0412 02:02:20.595782   30872 cache.go:63] save image to file "k8s.gcr.io/kube-apiserver:v1.18.0" -> "C:\\Users\\zhouji-pc\\.minikube\\cache\\images\\k8s.gcr.io\\kube-apiserver_v1.18.0" failed: nil image for k8s.gcr.io/kube-apiserver:v1.18.0: Get https://k8s.gcr.io/v2/: dial tcp [2404:6800:4008:c01::52]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.